defaults: &defaults
  docker:
    - image: circleci/python:3.6

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Installing pipenv
          command: |
            pip install --user pipenv
            echo 'export PATH=$PATH:$HOME/.local/bin' >> $BASH_ENV
      - run:
          name: Installing all dependencies (including dev ones)
          command: make dev
      - run:
          name: Running tests
          command: |
            mkdir test_results
            pipenv run nosetests --with-xunit --xunit-file=test_results/xunit.xml --cover-branches --with-coverage --cover-erase --cover-package=nyuki --cover-html --cover-html-dir=test_results/coverage
      - store_artifacts:
          path: test_results
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Installing Twine
          command: |
            pip install --user twine
            echo 'export PATH=$PATH:$HOME/.local/bin' >> $BASH_ENV
      - run:
          name: Deploying to Pypi
          command: ./deploy_to_pypi.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+){2}/
